version: '3'
services:
    feedback:
        build:
            context: ./
        depends_on:
            - grafana
        networks:
          - apns-feedback

    influxdb:
        image: influxdb
        container_name: influxdb
        hostname: influxdb
        restart: always
        expose:
          - 8086
        ports:
          - "8086:8086"
        volumes:
          - "${PWD}/data/influxdb:/var/lib/influxdb"
        networks:
          - apns-feedback

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        depends_on:
          - influxdb
        expose:
          - 3000
        ports:
          - "5000:3000"
        volumes:
          - "${PWD}/data/grafana:/var/lib/grafana"
        networks:
          - apns-feedback

networks:
  apns-feedback:
    driver: bridge